version: '3.5'

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    restart: always
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
    networks:
      - via-varejo-01
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "390MB"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: via-varejo
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
    networks:
      - via-varejo-01

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - via-varejo-01

networks:
  via-varejo-01:
    driver: bridge

volumes:
  postgres_data:
